name: Convert Conf to Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt  # 如果有额外依赖，可在requirements.txt中指定

    - name: Convert .conf to .plugin
      run: python convert_conf_to_plugin.py conf/example.conf plugin/example.plugin

    - name: Commit and push the result
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add plugin/example.plugin
        git commit -m "Convert .conf to .plugin"
        git push
