name: Convert Conf to Plugin

on:
  schedule:
    - cron:  '0 0 8 * * *'  # 每天早上8点运行
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Convert all .conf files to .plugin
      run: python convert_conf_to_plugin.py

    - name: Commit and push the result
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add plugin/
        git commit -m "Daily conversion of .conf to .plugin"
        git push
